description = "Disable miro-tasks plugin and stop automatic task tracking"

prompt = """
# Disable task tracking in Miro

This command disables tracking of tasks execution in Miro.

Run script ${extensionPath}/scripts/command-disable.sh
"""
